name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Backend
      - name: Build Backend Docker image
        run: |
          docker build -t anime-timetable/mal-backend:latest -f ./anime_recommender/Dockerfile ./anime_recommender

      # Build Frontend
      - name: Build Frontend Docker image
        run: |
          docker build -t anime-timetable/mal-frontend:latest -f ./anime_frontend/Dockerfile ./anime_frontend

      # Push Backend
      - name: Push Backend Docker image
        run: |
          docker push anime-timetable/mal-backend:latest

      # Push Frontend
      - name: Push Frontend Docker image
        run: |
          docker push anime-timetable/mal-frontend:latest